#!/usr/bin/env python3
"""Vendor the FontAwesome Free *solid* webfont and generate the ScoutKit icon catalog.

The Scout core font (`scoutIcons`) only ships a small glyph set, so the app self-hosts the full
FontAwesome Free solid style (1300+ glyphs) under the `scoutkit-icons` font family. This avoids a
CDN (the font is served from `apps/web/res/fonts`, copied into the static site next to Scout's own
fonts) and means *every* FontAwesome solid icon is registered once — `apps/web/src/main/fa-icons.ts`
becomes a complete, typed catalog (`faIcons.<NAME>` -> `font:scoutkit-icons <char>`), so adding a new
icon never requires editing the font again.

This script regenerates two committed artifacts from a FontAwesome Free install:

  * `apps/web/res/fonts/scoutkit-icons.woff2`  <- FontAwesome's prebuilt `fa-solid-900.woff2`
  * `apps/web/src/main/fa-icons.ts`            <- catalog generated from `metadata/icons.json`

FontAwesome Free: icons CC BY 4.0, fonts SIL OFL 1.1 (https://fontawesome.com/license/free).

Usage:
    python3 apps/web/scripts/generate-icons.py [path-to-fontawesome-free]

The FontAwesome base dir must contain `webfonts/fa-solid-900.woff2` and `metadata/icons.json`. If no
path is given, common locations are probed: the repo's
`node_modules/@fortawesome/fontawesome-free` (`npm i -D @fortawesome/fontawesome-free`) and the
Python `fontawesomefree` package (`pip install fontawesomefree`).
"""
import json
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
WEB = os.path.normpath(os.path.join(HERE, ".."))
REPO = os.path.normpath(os.path.join(WEB, "..", ".."))
FONT_FAMILY = "scoutkit-icons"
STYLE = "solid"

WOFF2_OUT = os.path.join(WEB, "res", "fonts", "scoutkit-icons.woff2")
CATALOG_OUT = os.path.join(WEB, "src", "main", "fa-icons.ts")


def find_fa_base() -> str:
    """Locate a FontAwesome Free base dir holding webfonts/ + metadata/icons.json."""
    candidates = []
    if len(sys.argv) > 1:
        candidates.append(sys.argv[1])
    candidates.append(os.path.join(REPO, "node_modules", "@fortawesome", "fontawesome-free"))
    candidates.append(os.path.join(WEB, "node_modules", "@fortawesome", "fontawesome-free"))
    try:
        import fontawesomefree  # type: ignore
        candidates.append(os.path.join(os.path.dirname(fontawesomefree.__file__), "static", "fontawesomefree"))
    except Exception:
        pass
    for base in candidates:
        if os.path.isfile(os.path.join(base, "webfonts", "fa-solid-900.woff2")) \
                and os.path.isfile(os.path.join(base, "metadata", "icons.json")):
            return base
    raise SystemExit(
        "FontAwesome Free not found. Pass its path as an argument, or install it via\n"
        "  npm i -D @fortawesome/fontawesome-free   (or)   pip install fontawesomefree")


def to_ident(name: str) -> str:
    """FontAwesome kebab-case name -> a valid SCREAMING_SNAKE TypeScript identifier."""
    ident = re.sub(r"[^0-9a-zA-Z]+", "_", name).upper().strip("_")
    if ident[0].isdigit():
        ident = "_" + ident  # e.g. '0' -> '_0', '42-group' -> '_42_GROUP'
    return ident


def solid_icons(meta: dict) -> dict:
    """name -> codepoint(int) for every icon offering the solid style, sorted by name."""
    out = {}
    for name, info in meta.items():
        styles = info.get("free") or info.get("styles") or []
        if STYLE in styles:
            out[name] = int(info["unicode"], 16)
    return dict(sorted(out.items()))


def main() -> None:
    base = find_fa_base()
    with open(os.path.join(base, "metadata", "icons.json"), encoding="utf-8") as f:
        meta = json.load(f)
    icons = solid_icons(meta)

    # Map each icon name to a unique TS identifier (assert no clashes after normalization).
    idents: dict[str, str] = {}
    for name in icons:
        ident = to_ident(name)
        if ident in idents:
            raise SystemExit(f"identifier clash: {name} and {idents[ident]} both -> {ident}")
        idents[ident] = name

    os.makedirs(os.path.dirname(WOFF2_OUT), exist_ok=True)
    shutil.copyfile(os.path.join(base, "webfonts", "fa-solid-900.woff2"), WOFF2_OUT)

    lines = [
        "/* eslint-disable */",
        "// AUTO-GENERATED by apps/web/scripts/generate-icons.py — do not edit by hand.",
        "//",
        "// Complete catalog of the FontAwesome Free solid icon set, registered against the self-hosted",
        "// `scoutkit-icons` font (apps/web/res/fonts/scoutkit-icons.woff2, @font-face in",
        "// theme/scoutkit.less). Each value is a Scout `iconId` usable on any widget's `iconId`",
        "// property. FontAwesome Free: icons CC BY 4.0, fonts SIL OFL 1.1.",
        "//",
        f"// {len(icons)} icons. Reference via the curated `Icons` export in ./Icons.ts.",
        "export const faIcons = {",
    ]
    for ident, name in sorted(idents.items()):
        cp = icons[name]
        lines.append(f"  /** FontAwesome `{name}`. */")
        lines.append(f"  {ident}: 'font:{FONT_FAMILY} \\u{cp:04X}',")
    lines.append("} as const;")
    lines.append("")
    with open(CATALOG_OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"wrote {WOFF2_OUT}")
    print(f"wrote {CATALOG_OUT} ({len(icons)} icons) from {base}")


if __name__ == "__main__":
    main()
